project_id = "force-collector"

[api]
port = 54321
schemas = ["public", "storage", "auth"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[auth]
enabled = true
site_url = "http://localhost:8081"
additional_redirect_urls = []

[storage]
enabled = true

[functions]
[functions.health]
verify_jwt = false
[functions.api]
verify_jwt = true
